config/routes.rb
SSTaskTracker::Application.routes.draw do

  get '/users/sign_up', to: redirect('/users/sign_in')

  devise_for :users
  
  get 'backlog_items/get_items/:item_type/:status/:parent_id' => 'backlog_items#get_items'

  get 'backlog_items/get_active_sprint/:parent_id' => 'backlog_items#get_active_sprint'
  put 'backlog_items/get_active_sprint/:parent_id/:id', to: redirect('/backlog_items/%{id}')
  patch 'backlog_items/get_active_sprint/:parent_id/:id', to: redirect('/backlog_items/%{id}')
  
  get 'backlog_items/get_tasks/:sprint_id' => 'backlog_items#get_tasks'
  get 'backlog_items/get_stories/:sprint_id' => 'backlog_items#get_stories'

  get 'projects/info/:id' => 'projects#get_project_info'
  
  get 'tasks/for-project/:id' => 'tasks#get_tasks'
   
  get "projects/for-user/:id" => "projects#get_projects"

  get "stories/for-project/:id" => "stories#index" 

  get "active-stories/for-project/:id" => "stories#get_stories_for_sprint"

  get "teams-candidates/for-team/:id" => "users#get_all", as: :user

  get "teams/for-project/:id" => "teams#get_teams"

  get 'users/for-team/:id' => 'team_members#get_team_members', as: :team_member

  get "roles/for-user" => "users#get_roles"

  get "roles/for-user/:id" => "users#get_roles"
   
  resources :projects

  resources :permissions
  
  resources :dash_buttons
	
  resources :backlog_items

  resources :stories

  resources :teams

  resources :tasks

  resources :sprints

  resources :team_members

  get ':params(/:tmp(/:tmp))' => 'app#main'

  get "app/main"

  root 'app#main'

  

end

app/models/dash_button.rb
class DashButton < ActiveRecord::Base
	has_one :permission
end

app/controllers/dash_buttons_controller.rb
class DashButtonsController < ApplicationController
  before_action :set_dash_button, only: [:show, :edit, :update, :destroy]

  # GET /dash_buttons
  # GET /dash_buttons.json
  def index
    @dash_buttons = DashButton.all
	
  end

  # GET /dash_buttons/1
  # GET /dash_buttons/1.json
  def show
  end

  # GET /dash_buttons/new
  def new
    @dash_button = DashButton.new
  end

  # GET /dash_buttons/1/edit
  def edit
  end

  # POST /dash_buttons
  # POST /dash_buttons.json
  def create
    @dash_button = DashButton.new(dash_button_params)

    respond_to do |format|
      if @dash_button.save
        format.html { redirect_to @dash_button, notice: 'Dash button was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dash_button }
      else
        format.html { render action: 'new' }
        format.json { render json: @dash_button.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dash_buttons/1
  # PATCH/PUT /dash_buttons/1.json
  def update
    respond_to do |format|
      if @dash_button.update(dash_button_params)
        format.html { redirect_to @dash_button, notice: 'Dash button was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dash_button.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dash_buttons/1
  # DELETE /dash_buttons/1.json
  def destroy
    @dash_button.destroy
    respond_to do |format|
      format.html { redirect_to dash_buttons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dash_button
      @dash_button = DashButton.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dash_button_params
      params.require(:dash_button).permit(:btn_content, :btn_type, :permission)
    end
end

app/helpers/dash_buttons_helper.rb
module DashButtonsHelper
end

app/views/dash_buttons/_form.html.erb
<%= form_for(@dash_button) do |f| %>
  <% if @dash_button.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dash_button.errors.count, "error") %> prohibited this dash_button from being saved:</h2>

      <ul>
      <% @dash_button.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :btn_content %><br>
    <%= f.text_field :btn_content %>
  </div>
  <div class="field">
    <%= f.label :btn_type %><br>
    <%= f.text_field :btn_type %>
  </div>
  <div class="field">
    <%= f.label :permission %><br>
    <%= f.text_field :permission %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dash_buttons/edit.html.erb
<h1>Editing dash_button</h1>

<%= render 'form' %>

<%= link_to 'Show', @dash_button %> |
<%= link_to 'Back', dash_buttons_path %>

app/views/dash_buttons/index.html.erb
<h1>Listing dash_buttons</h1>

<table>
  <thead>
    <tr>
      <th>Btn content</th>
      <th>Btn type</th>
      <th>Permission</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dash_buttons.each do |dash_button| %>
      <tr>
        <td><%= dash_button.btn_content %></td>
        <td><%= dash_button.btn_type %></td>
        <td><%= dash_button.permission %></td>
        <td><%= link_to 'Show', dash_button %></td>
        <td><%= link_to 'Edit', edit_dash_button_path(dash_button) %></td>
        <td><%= link_to 'Destroy', dash_button, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dash button', new_dash_button_path %>

app/views/dash_buttons/new.html.erb
<h1>New dash_button</h1>

<%= render 'form' %>

<%= link_to 'Back', dash_buttons_path %>

app/views/dash_buttons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Btn content:</strong>
  <%= @dash_button.btn_content %>
</p>

<p>
  <strong>Btn type:</strong>
  <%= @dash_button.btn_type %>
</p>

<p>
  <strong>Permission:</strong>
  <%= @dash_button.permission %>
</p>

<%= link_to 'Edit', edit_dash_button_path(@dash_button) %> |
<%= link_to 'Back', dash_buttons_path %>