config/routes.rb
SSTaskTracker::Application.routes.draw do

  get '/users/sign_up', to: redirect('/users/sign_in')

  devise_for :users
  
  get 'backlog_items/get_items/:item_type/:status/:parent_id' => 'backlog_items#get_items'

  get 'backlog_items/get_active_sprint/:parent_id' => 'backlog_items#get_active_sprint'
  put 'backlog_items/get_active_sprint/:parent_id/:id', to: redirect('/backlog_items/%{id}')
  patch 'backlog_items/get_active_sprint/:parent_id/:id', to: redirect('/backlog_items/%{id}')
  
  get 'backlog_items/get_tasks/:sprint_id' => 'backlog_items#get_tasks'
  get 'backlog_items/get_stories/:sprint_id' => 'backlog_items#get_stories'

  get 'projects/info/:id' => 'projects#get_project_info'
  
  get 'tasks/for-project/:id' => 'tasks#get_tasks'
   
  get "projects/for-user/:id" => "projects#get_projects"

  get "stories/for-project/:id" => "stories#index" 

  get "active-stories/for-project/:id" => "stories#get_stories_for_sprint"

  get "teams-candidates/for-team/:id" => "users#get_all", as: :user

  get "teams/for-project/:id" => "teams#get_teams"

  get 'users/for-team/:id' => 'team_members#get_team_members', as: :team_member

  get "roles/for-user" => "users#get_roles"

  get "roles/for-user/:id" => "users#get_roles"
   
  resources :projects

  resources :permissions
  
  resources :dash_buttons
	
  resources :backlog_items

  resources :stories

  resources :teams

  resources :tasks

  resources :sprints

  resources :team_members

  get ':params(/:tmp(/:tmp))' => 'app#main'

  get "app/main"

  root 'app#main'

  

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
    belongs_to :user
    belongs_to :team
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]
  #skip_before_filter  :verify_authenticity_token
  
  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all
  end
  
  def get_team_members
    @team = Team.find(params[:id])
    @team_members = []
    
    @team.team_members.each do |team_member|
      @user_c = {
        :id =>  team_member.id,
        :first_name => team_member.user.first_name,
        :last_name => team_member.user.last_name,
        :role =>  team_member.role,
        :user_id => team_member.user_id
      }
      @team_members.push(@user_c)
    end
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render action: 'show', status: :created, location: @team_member }
      else
        format.html { render action: 'new' }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.require(:team_member).permit(:user_id, :team_id, :role)
    end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= form_for(@team_member) do |f| %>
  <% if @team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
      <% @team_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_members/edit.html.erb
<h1>Editing team_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

app/views/team_members/get_team_members.html.erb
<h1>Listing team_members</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Team</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= team_member[:id] %></td>
        <td><%= team_member[:first_name] %></td>
        <td><%= team_member[:last_name] %></td>
        <td><%= team_member[:role] %></td>

        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  

app/views/team_members/index.html.erb
<h1>Listing team_members</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Team</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= team_member.user_id %></td>
        <td><%= team_member.team_id %></td>
        <td><%= team_member.role %></td>
        <td><%= team_member.id %></td>

        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    <% @team_members.each do |team_member| %>
       <ul>
          <li>
            <% if team_member.role == 'watcher'%> 
              role = <%= team_member.role %>;
              user id = <%= team_member.user.id %>;
              name = <%= team_member.user.first_name %>;
              team id = <%= team_member.team.id %>
              project_id = <%= team_member.team.project_id %>;
              project = <%= team_member.team.project.title %>

              <%end%>
          </li>
        </ul>
    <% end %>   

  </tbody>
</table>

<br>

<%= link_to 'New Team member', new_team_member_path %>

app/views/team_members/new.html.erb
<h1>New team_member</h1>

<%= render 'form' %>

<%= link_to 'Back', team_members_path %>

app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @team_member.user_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @team_member.team_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @team_member.role %>
</p>

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>