config/routes.rb
SSTaskTracker::Application.routes.draw do

  get '/users/sign_up', to: redirect('/users/sign_in')

  devise_for :users
  
  get 'backlog_items/get_items/:item_type/:status/:parent_id' => 'backlog_items#get_items'

  get 'backlog_items/get_active_sprint/:parent_id' => 'backlog_items#get_active_sprint'
  put 'backlog_items/get_active_sprint/:parent_id/:id', to: redirect('/backlog_items/%{id}')
  patch 'backlog_items/get_active_sprint/:parent_id/:id', to: redirect('/backlog_items/%{id}')
  
  get 'backlog_items/get_tasks/:sprint_id' => 'backlog_items#get_tasks'
  get 'backlog_items/get_stories/:sprint_id' => 'backlog_items#get_stories'

  get 'projects/info/:id' => 'projects#get_project_info'
  
  get 'tasks/for-project/:id' => 'tasks#get_tasks'
   
  get "projects/for-user/:id" => "projects#get_projects"

  get "stories/for-project/:id" => "stories#index" 

  get "active-stories/for-project/:id" => "stories#get_stories_for_sprint"

  get "teams-candidates/for-team/:id" => "users#get_all", as: :user

  get "teams/for-project/:id" => "teams#get_teams"

  get 'users/for-team/:id' => 'team_members#get_team_members', as: :team_member

  get "roles/for-user" => "users#get_roles"

  get "roles/for-user/:id" => "users#get_roles"
   
  resources :projects

  resources :permissions
  
  resources :dash_buttons
	
  resources :backlog_items

  resources :stories

  resources :teams

  resources :tasks

  resources :sprints

  resources :team_members

  get ':params(/:tmp(/:tmp))' => 'app#main'

  get "app/main"

  root 'app#main'

  

end

app/models/backlog_item.rb
class BacklogItem < ActiveRecord::Base
end

app/controllers/backlog_items_controller.rb
class BacklogItemsController < ApplicationController
  before_action :set_backlog_item, only: [:show, :edit, :update, :destroy]

  # GET /backlog_items
  # GET /backlog_items.json
  def index
    @backlog_items = BacklogItem.all
  end

  # GET /backlog_items/1
  # GET /backlog_items/1.json
  def show
  end

  # GET /backlog_items/new
  def new
    @backlog_item = BacklogItem.new
  end

  # GET /backlog_items/1/edit
  def edit
  end

  # POST /backlog_items
  # POST /backlog_items.json
  def create
  
    @backlog_item = BacklogItem.new(backlog_item_all_params)
    
    if @backlog_item.item_type == "sprint"
      if params.has_key?("start_date") && params.has_key?("end_date")
        @backlog_item.info = {start_date: params[:start], end_date: params[:end]}.to_json
      end
    end

    respond_to do |format|
      if @backlog_item.save
        format.html { redirect_to @backlog_item, notice: 'Backlog item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @backlog_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @backlog_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backlog_items/1
  # PATCH/PUT /backlog_items/1.json
  def update
    if @backlog_item.item_type == "sprint"
      if params.has_key?("start_date") && params.has_key?("end_date")
        @backlog_item.update(info: {start_date: params[:start], end_date: params[:end]}.to_json)
      end

      if params[:backlog_item][:status] == 'failed'
        @stories = BacklogItem.where(
          "item_type = 'story' AND (NOT status = 'product') AND parent_id = ?",
          params[:id]
        )

        @stories.each do |story|
          story.update(status: "product", parent_id: @backlog_item[:parent_id])
        end
      end
    else
      if @backlog_item.item_type == "task" && params[:status] == "done"
        @tasks = BacklogItem.where(
          "item_type = 'task' AND (Not status = 'done') AND parent_id = ? AND id !=?",
          params[:parent_id], params[:id]
        )
        if(@tasks.size == 0)
          @story = BacklogItem.where(
            "id = ?", params[:parent_id]
          ).take
          time = Time.now.strftime("%Y/%m/%d %H:%M:%S")
          @story.update(info: {end_date: time}.to_json)
        end
      end
    end

    respond_to do |format|
      if @backlog_item.update(backlog_item_all_params)
        format.html { redirect_to @backlog_item, notice: 'Backlog item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @backlog_item.errors, status: :unprocessable_entity }
      end
    end

    if @backlog_item.item_type == "story"
      if params[:backlog_item][:status] == 'done'
        time = Time.now.strftime("%Y/%m/%d %H:%M:%S");
        @backlog_item.update(info: {end_date: time}.to_json)
      end
    end
  end

  # DELETE /backlog_items/1
  # DELETE /backlog_items/1.json
  def destroy
    @backlog_item.destroy
    respond_to do |format|
      format.html { redirect_to backlog_items_url }
      format.json { head :no_content }
    end
  end
  
  # GET /backlog_items/get_items/:item_type/:status/:parent_id
  def get_items
    @backlog_items = BacklogItem.where(
		  "item_type =? AND status=? AND parent_id=?",
		  params[:item_type], params[:status], params[:parent_id]
    )

	  @backlog_items.each do |backlog_item|
      
      if backlog_item.item_type == "sprint"
        info = ActiveSupport::JSON.decode(backlog_item[:info])
        backlog_item[:info] = info
      end
    end
  end

  def get_active_sprint
    @backlog_item = BacklogItem.where(
      "item_type ='sprint' AND status='active' AND parent_id=?",
      params[:parent_id]
    ).take
    
    if @backlog_item
      info = ActiveSupport::JSON.decode(@backlog_item[:info])
      @backlog_item[:info] = info
    end
  end
  
  def get_tasks
    @sprint_id = params[:sprint_id]
	
  	@stories = BacklogItem.where(
  		"item_type = ? AND status = ? AND parent_id = ?",
  		"story", "sprint",	@sprint_id
  	)

    @stories_without_task = BacklogItem.where(
      "item_type = ? AND (status = ? OR status = ? OR status = ? OR status = ?) AND parent_id = ?",
      "story", "todo", "progress", "verify", "done",  @sprint_id
    )
	
  	@all_tasks = []

  	@stories.each do |story|
  		@tasks = BacklogItem.where(
    		"item_type = ? AND parent_id=?",
    		"task", story.id
  		)
    	
      @all_tasks.push(@tasks)
  	end
	  
    @all_tasks.push(@stories_without_task)

    @all_tasks = @all_tasks.flatten
	
	  respond_to do |format|
      format.json { render json:  @all_tasks }
    end
  end

  def get_stories
    @sprint_id = params[:sprint_id]
  
    @stories = BacklogItem.where(
      "item_type = ? AND (NOT status = 'product') AND parent_id = ?",
      "story",  @sprint_id
    )

    @stories.each do |story|
      info = ActiveSupport::JSON.decode(story[:info])
      story[:info] = info
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backlog_item
      @backlog_item = BacklogItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backlog_item_params
      params.require(:backlog_item).permit(:title, :description, :estimation, :parent_id, :status, :item_type, :info)
    end

    def backlog_item_all_params
      params.require(:backlog_item).permit(:title, :description, :estimation, :parent_id, :status, :item_type, :info)
    end

end

app/helpers/backlog_items_helper.rb
module BacklogItemsHelper
end

app/views/backlog_items/_form.html.erb
<%= form_for(@backlog_item) do |f| %>
  <% if @backlog_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@backlog_item.errors.count, "error") %> prohibited this backlog_item from being saved:</h2>

      <ul>
      <% @backlog_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :estimation %><br>
    <%= f.number_field :estimation %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :item_type %><br>
    <%= f.text_field :item_type %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backlog_items/edit.html.erb
<h1>Editing backlog_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @backlog_item %> |
<%= link_to 'Back', backlog_items_path %>

app/views/backlog_items/get_items.html.erb
<div style="
  background-color: white;
">
<h1>Listing backlog_items</h1>

<table>
  <thead>
    <tr>
    <th>Id</th>
      <th>Title</th>
      <th>Description</th>
      <th>Estimation</th>
      <th>Parent</th>
      <th>Status</th>
      <th>Item type</th>
      <th>Info</th>
      <th>start_at</th>
      <th>end_at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @backlog_items.each do |backlog_item| %>
      <tr>
    <td><%= backlog_item.id %></td>
        <td><%= backlog_item.title %></td>
        <td><%= backlog_item.description %></td>
        <td><%= backlog_item.estimation %></td>
        <td><%= backlog_item.parent_id %></td>
        <td><%= backlog_item.status %></td>
        <td><%= backlog_item.item_type %></td>
        <td><%= backlog_item.info %></td>
        <td><% if backlog_item.item_type == "sprint" %><%= backlog_item.info["start_date"] %><% end %></td>
        <td><% if backlog_item.item_type == "sprint" %><%= backlog_item.info["end_date"] %><% end %></td>
        <td><%= link_to 'Show', backlog_item %></td>
        <td><%= link_to 'Edit', edit_backlog_item_path(backlog_item) %></td>
        <td><%= link_to 'Destroy', backlog_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backlog item', new_backlog_item_path %>
</div>

app/views/backlog_items/get_tasks.html.erb
<h1>Listing backlog_items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Estimation</th>
      <th>Parent</th>
      <th>Status</th>
      <th>Item type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @backlog_items.each do |backlog_item| %>
      <tr>
        <td><%= backlog_item.title %></td>
        <td><%= backlog_item.description %></td>
        <td><%= backlog_item.estimation %></td>
        <td><%= backlog_item.parent_id %></td>
        <td><%= backlog_item.status %></td>
        <td><%= backlog_item.item_type %></td>
        <td><%= link_to 'Show', backlog_item %></td>
        <td><%= link_to 'Edit', edit_backlog_item_path(backlog_item) %></td>
        <td><%= link_to 'Destroy', backlog_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backlog item', new_backlog_item_path %>

app/views/backlog_items/index.html.erb
<div style="
  background-color: white;
">
<h1>Listing backlog_items</h1>

<table>
  <thead>
    <tr>
   	  <th>Id</th>
      <th>Title</th>
      <th>Description</th>
      <th>Estimation</th>
      <th>Parent</th>
      <th>Status</th>
      <th>Item type</th>
      <th>Info</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @backlog_items.each do |backlog_item| %>
      <tr>
		    <td><%= backlog_item.id %></td>
        <td><%= backlog_item.title %></td>
        <td><%= backlog_item.description %></td>
        <td><%= backlog_item.estimation %></td>
        <td><%= backlog_item.parent_id %></td>
        <td><%= backlog_item.status %></td>
        <td><%= backlog_item.item_type %></td>
        <td><%= backlog_item.info %></td>
        <td><%= link_to 'Show', backlog_item %></td>
        <td><%= link_to 'Edit', edit_backlog_item_path(backlog_item) %></td>
        <td><%= link_to 'Destroy', backlog_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backlog item', new_backlog_item_path %>
</div>

app/views/backlog_items/new.html.erb
<h1>New backlog_item</h1>

<%= render 'form' %>

<%= link_to 'Back', backlog_items_path %>

app/views/backlog_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @backlog_item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @backlog_item.description %>
</p>

<p>
  <strong>Estimation:</strong>
  <%= @backlog_item.estimation %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @backlog_item.parent_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @backlog_item.status %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @backlog_item.item_type %>
</p>

<% if @backlog_item.item_type == "sprint" %>
<p>
  <strong>Info:</strong>
  <%= @backlog_item.info %>
</p>
<% end %>

<%= link_to 'Edit', edit_backlog_item_path(@backlog_item) %> |
<%= link_to 'Back', backlog_items_path %>